# Generated by Django 4.2.2 on 2023-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
