# Generated by Django 4.2.2 on 2023-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='date_return',
            field=models.DateField(blank=True),
        ),
    ]
