# Generated by Django 4.2.2 on 2023-06-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_employee_date_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='full_name',
        ),
    ]
