# Generated by Django 4.2.2 on 2023-07-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_emp_date_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
